### ISSUE TITLE
Discord calling doesn't work, YouTube videos glitching out

### ISSUE THREAD

**Issue by sn382r9g7r82buw423** [HENRYMARTIN5/ChromeBox#2]
Discord just says "Unsupported browser" and simply doesn't let me join any voice calls. Another issue is that some youtube videos glitch out and when you attempt to open them, it just shows a bunch of flashing green lights

**Comment by HENRYMARTIN5** [comment]
Consider a different method of bypassing restrictions, this one is outdated and was only made as an experiment. If you need a guide, take a look at: https://chromebook-guide.github.io/
